/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Speciality = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const WorkAvailability = IDL.Variant({
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const ElectricianQualification = IDL.Variant({
  'eeeDiploma' : IDL.Null,
  'electronicElectricalEngineering' : IDL.Null,
  'itiElectrician' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'verifiedPendingAssignment' : IDL.Null,
  'rejected' : IDL.Text,
});
export const ElectricianView = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'assignedWorkOrders' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'workAvailability' : WorkAvailability,
  'isAvailable' : IDL.Bool,
  'specialist' : Speciality,
  'email' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'qualification' : ElectricianQualification,
  'verificationStatus' : VerificationStatus,
});
export const Time = IDL.Int;
export const PublicJobAlertSubscription = IDL.Record({ 'subscribedAt' : Time });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addElectrician' : IDL.Func(
      [
        IDL.Text,
        Speciality,
        WorkAvailability,
        ElectricianQualification,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignElectricianToWorkOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'findElectricianById' : IDL.Func([IDL.Nat], [ElectricianView], []),
  'getAllElectricians' : IDL.Func([], [IDL.Vec(ElectricianView)], []),
  'getAllJobAlertSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(PublicJobAlertSubscription)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingElectricians' : IDL.Func([], [IDL.Vec(ElectricianView)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribedToJobAlerts' : IDL.Func([], [IDL.Bool], ['query']),
  'removeElectrician' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribeToJobAlerts' : IDL.Func([], [], []),
  'updateElectrician' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(Speciality),
        IDL.Opt(IDL.Bool),
        IDL.Opt(WorkAvailability),
        IDL.Opt(ElectricianQualification),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Speciality = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const WorkAvailability = IDL.Variant({
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const ElectricianQualification = IDL.Variant({
    'eeeDiploma' : IDL.Null,
    'electronicElectricalEngineering' : IDL.Null,
    'itiElectrician' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'verifiedPendingAssignment' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const ElectricianView = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'assignedWorkOrders' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'workAvailability' : WorkAvailability,
    'isAvailable' : IDL.Bool,
    'specialist' : Speciality,
    'email' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'qualification' : ElectricianQualification,
    'verificationStatus' : VerificationStatus,
  });
  const Time = IDL.Int;
  const PublicJobAlertSubscription = IDL.Record({ 'subscribedAt' : Time });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addElectrician' : IDL.Func(
        [
          IDL.Text,
          Speciality,
          WorkAvailability,
          ElectricianQualification,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignElectricianToWorkOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'findElectricianById' : IDL.Func([IDL.Nat], [ElectricianView], []),
    'getAllElectricians' : IDL.Func([], [IDL.Vec(ElectricianView)], []),
    'getAllJobAlertSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(PublicJobAlertSubscription)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingElectricians' : IDL.Func([], [IDL.Vec(ElectricianView)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribedToJobAlerts' : IDL.Func([], [IDL.Bool], ['query']),
    'removeElectrician' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribeToJobAlerts' : IDL.Func([], [], []),
    'updateElectrician' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(Speciality),
          IDL.Opt(IDL.Bool),
          IDL.Opt(WorkAvailability),
          IDL.Opt(ElectricianQualification),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };