/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ElectricianQualification = { 'eeeDiploma' : null } |
  { 'electronicElectricalEngineering' : null } |
  { 'itiElectrician' : null };
export interface ElectricianView {
  'id' : bigint,
  'paymentMethod' : string,
  'assignedWorkOrders' : Array<bigint>,
  'name' : string,
  'hourlyRate' : bigint,
  'workAvailability' : WorkAvailability,
  'isAvailable' : boolean,
  'specialist' : Speciality,
  'email' : string,
  'currency' : string,
  'address' : string,
  'qualification' : ElectricianQualification,
  'verificationStatus' : VerificationStatus,
}
export interface PublicJobAlertSubscription { 'subscribedAt' : Time }
export type Speciality = { 'commercial' : null } |
  { 'residential' : null } |
  { 'industrial' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'verifiedPendingAssignment' : null } |
  { 'rejected' : string };
export type WorkAvailability = { 'partTime' : null } |
  { 'fullTime' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addElectrician' : ActorMethod<
    [
      string,
      Speciality,
      WorkAvailability,
      ElectricianQualification,
      string,
      string,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignElectricianToWorkOrder' : ActorMethod<[bigint, bigint], undefined>,
  'findElectricianById' : ActorMethod<[bigint], ElectricianView>,
  'getAllElectricians' : ActorMethod<[], Array<ElectricianView>>,
  'getAllJobAlertSubscriptions' : ActorMethod<
    [],
    Array<PublicJobAlertSubscription>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingElectricians' : ActorMethod<[], Array<ElectricianView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribedToJobAlerts' : ActorMethod<[], boolean>,
  'removeElectrician' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeToJobAlerts' : ActorMethod<[], undefined>,
  'updateElectrician' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [Speciality],
      [] | [boolean],
      [] | [WorkAvailability],
      [] | [ElectricianQualification],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];