/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Speciality = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Electrician = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'specialist' : Speciality,
  'email' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
});
export const WorkOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Rating = IDL.Record({ 'comment' : IDL.Text, 'rating' : IDL.Nat });
export const Time = IDL.Int;
export const WorkOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : WorkOrderStatus,
  'title' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : IDL.Text,
  'workerRating' : IDL.Opt(Rating),
  'createdAt' : Time,
  'customerRating' : IDL.Opt(Rating),
  'preferredEducation' : IDL.Text,
  'description' : IDL.Text,
  'customerAddress' : IDL.Text,
  'issuedElectrician' : IDL.Nat,
  'priority' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'paymentAmount' : IDL.Nat,
  'location' : IDL.Text,
});
export const RepairServiceType = IDL.Variant({
  'ac' : IDL.Null,
  'ceilingFan' : IDL.Null,
  'tableFan' : IDL.Null,
  'fridge' : IDL.Null,
  'television' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addElectrician' : IDL.Func(
      [IDL.Text, Speciality, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignElectricianToWorkOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createWorkOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'findElectricianById' : IDL.Func([IDL.Nat], [Electrician], ['query']),
  'findWorkOrderById' : IDL.Func([IDL.Nat], [WorkOrder], ['query']),
  'getAllElectricians' : IDL.Func([], [IDL.Vec(Electrician)], ['query']),
  'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
  'getAvailableServices' : IDL.Func(
      [],
      [IDL.Vec(RepairServiceType)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkOrdersByElectrician' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkOrder)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeElectrician' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCustomerRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'submitWorkerRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'updateElectrician' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(Speciality),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateWorkOrderPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, PaymentStatus],
      [],
      [],
    ),
  'updateWorkOrderStatus' : IDL.Func([IDL.Nat, WorkOrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Speciality = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Electrician = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'specialist' : Speciality,
    'email' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
  });
  const WorkOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Rating = IDL.Record({ 'comment' : IDL.Text, 'rating' : IDL.Nat });
  const Time = IDL.Int;
  const WorkOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : WorkOrderStatus,
    'title' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : IDL.Text,
    'workerRating' : IDL.Opt(Rating),
    'createdAt' : Time,
    'customerRating' : IDL.Opt(Rating),
    'preferredEducation' : IDL.Text,
    'description' : IDL.Text,
    'customerAddress' : IDL.Text,
    'issuedElectrician' : IDL.Nat,
    'priority' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'paymentAmount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const RepairServiceType = IDL.Variant({
    'ac' : IDL.Null,
    'ceilingFan' : IDL.Null,
    'tableFan' : IDL.Null,
    'fridge' : IDL.Null,
    'television' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addElectrician' : IDL.Func(
        [IDL.Text, Speciality, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignElectricianToWorkOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createWorkOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'findElectricianById' : IDL.Func([IDL.Nat], [Electrician], ['query']),
    'findWorkOrderById' : IDL.Func([IDL.Nat], [WorkOrder], ['query']),
    'getAllElectricians' : IDL.Func([], [IDL.Vec(Electrician)], ['query']),
    'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
    'getAvailableServices' : IDL.Func(
        [],
        [IDL.Vec(RepairServiceType)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkOrdersByElectrician' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkOrder)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeElectrician' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCustomerRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'submitWorkerRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'updateElectrician' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(Speciality),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateWorkOrderPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, PaymentStatus],
        [],
        [],
      ),
    'updateWorkOrderStatus' : IDL.Func([IDL.Nat, WorkOrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };