/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationProcessStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'verifiedPendingAssignment' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface ChecklistItem {
  'id' : string,
  'order' : bigint,
  'completed' : boolean,
  'taskLabel' : string,
}
export interface Electrician {
  'id' : bigint,
  'paymentMethod' : string,
  'name' : string,
  'hourlyRate' : bigint,
  'workAvailability' : WorkAvailability,
  'isAvailable' : boolean,
  'specialist' : Speciality,
  'email' : string,
  'currency' : string,
  'address' : string,
  'qualification' : ElectricianQualification,
  'verificationStatus' : VerificationStatus,
}
export type ElectricianQualification = { 'eeeDiploma' : null } |
  { 'electronicElectricalEngineering' : null } |
  { 'itiElectrician' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'confirmed' : null } |
  { 'flagged' : string };
export interface PublicJobAlertSubscription { 'subscribedAt' : Time }
export interface Rating { 'comment' : string, 'rating' : bigint }
export type RepairServiceType = { 'electronicRepair' : null } |
  { 'electrician' : null } |
  { 'fridgeRepairWork' : null } |
  { 'acTechnician' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Speciality = { 'commercial' : null } |
  { 'residential' : null } |
  { 'industrial' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'verifiedPendingAssignment' : null } |
  { 'rejected' : string };
export type WorkAvailability = { 'partTime' : null } |
  { 'fullTime' : null };
export interface WorkOrder {
  'id' : bigint,
  'status' : WorkOrderStatus,
  'title' : string,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : string,
  'workerRating' : [] | [Rating],
  'createdAt' : Time,
  'customerRating' : [] | [Rating],
  'preferredEducation' : ElectricianQualification,
  'description' : string,
  'applicationStatus' : ApplicationProcessStatus,
  'customerAddress' : string,
  'issuedElectrician' : [] | [bigint],
  'customerContactNumber' : string,
  'priority' : bigint,
  'customerEmail' : string,
  'paymentAmount' : bigint,
  'location' : string,
  'verificationStatus' : VerificationStatus,
}
export interface WorkOrderApplication {
  'applicant' : Principal,
  'appliedAt' : Time,
  'workOrderId' : bigint,
}
export type WorkOrderStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptWorkOrder' : ActorMethod<[bigint], undefined>,
  'addElectrician' : ActorMethod<
    [
      string,
      Speciality,
      WorkAvailability,
      ElectricianQualification,
      string,
      string,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'applyForWorkOrder' : ActorMethod<[bigint], undefined>,
  'approveElectrician' : ActorMethod<[bigint], undefined>,
  'approveJobApplication' : ActorMethod<[bigint, Principal], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'approveWorkOrder' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignElectricianToWorkOrder' : ActorMethod<[bigint, bigint], undefined>,
  'createFixedPriceWorkOrder' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      ElectricianQualification,
    ],
    bigint
  >,
  'createWorkOrder' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      string,
      string,
      string,
      bigint,
      string,
      ElectricianQualification,
    ],
    bigint
  >,
  'declineWorkOrder' : ActorMethod<[bigint], undefined>,
  'findElectricianById' : ActorMethod<[bigint], Electrician>,
  'findWorkOrderById' : ActorMethod<[bigint], WorkOrder>,
  'flagPayment' : ActorMethod<[bigint, string], undefined>,
  'getAllElectricians' : ActorMethod<[], Array<Electrician>>,
  'getAllJobAlertSubscriptions' : ActorMethod<
    [],
    Array<PublicJobAlertSubscription>
  >,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getAvailableServices' : ActorMethod<[], Array<RepairServiceType>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getPendingElectricians' : ActorMethod<[], Array<Electrician>>,
  'getPendingJobApplications' : ActorMethod<[], Array<WorkOrder>>,
  'getPendingPayments' : ActorMethod<[], Array<WorkOrder>>,
  'getPendingWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedApplications' : ActorMethod<[], Array<WorkOrder>>,
  'getWorkOrderApplication' : ActorMethod<
    [bigint],
    [] | [WorkOrderApplication]
  >,
  'getWorkOrderConfirmation' : ActorMethod<
    [bigint],
    { 'status' : WorkOrderStatus, 'workOrderId' : bigint }
  >,
  'getWorkOrdersByApplicationStatus' : ActorMethod<
    [ApplicationProcessStatus],
    Array<WorkOrder>
  >,
  'getWorkOrdersByElectrician' : ActorMethod<[bigint], Array<WorkOrder>>,
  'getWorkerChecklist' : ActorMethod<[string], Array<ChecklistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribedToJobAlerts' : ActorMethod<[], boolean>,
  'rejectElectrician' : ActorMethod<[bigint, string], undefined>,
  'rejectJobApplication' : ActorMethod<[bigint, Principal, string], undefined>,
  'rejectWorkOrder' : ActorMethod<[bigint, string], undefined>,
  'removeElectrician' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCustomerRating' : ActorMethod<[bigint, bigint, string], undefined>,
  'submitWorkerRating' : ActorMethod<[bigint, bigint, string], undefined>,
  'subscribeToJobAlerts' : ActorMethod<[], undefined>,
  'updateApplicationStatusForWorkOrder' : ActorMethod<
    [bigint, ApplicationProcessStatus],
    undefined
  >,
  'updateChecklistItem' : ActorMethod<[string, string, boolean], Result>,
  'updateElectrician' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [Speciality],
      [] | [boolean],
      [] | [WorkAvailability],
      [] | [ElectricianQualification],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateWorkOrderPayment' : ActorMethod<
    [bigint, bigint, string, PaymentStatus],
    undefined
  >,
  'updateWorkOrderStatus' : ActorMethod<[bigint, WorkOrderStatus], undefined>,
  'verifyAndMoveToQueue' : ActorMethod<[bigint], undefined>,
  'verifyApplication' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];