/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Electrician {
  'id' : bigint,
  'paymentMethod' : string,
  'name' : string,
  'hourlyRate' : bigint,
  'isAvailable' : boolean,
  'specialist' : Speciality,
  'email' : string,
  'currency' : string,
  'address' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface Rating { 'comment' : string, 'rating' : bigint }
export type RepairServiceType = { 'ac' : null } |
  { 'ceilingFan' : null } |
  { 'tableFan' : null } |
  { 'fridge' : null } |
  { 'television' : null };
export type Speciality = { 'commercial' : null } |
  { 'residential' : null } |
  { 'industrial' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkOrder {
  'id' : bigint,
  'status' : WorkOrderStatus,
  'title' : string,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : string,
  'workerRating' : [] | [Rating],
  'createdAt' : Time,
  'customerRating' : [] | [Rating],
  'preferredEducation' : string,
  'description' : string,
  'customerAddress' : string,
  'issuedElectrician' : bigint,
  'priority' : bigint,
  'customerEmail' : string,
  'paymentAmount' : bigint,
  'location' : string,
}
export type WorkOrderStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addElectrician' : ActorMethod<
    [string, Speciality, string, string, bigint, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignElectricianToWorkOrder' : ActorMethod<[bigint, bigint], undefined>,
  'createWorkOrder' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'findElectricianById' : ActorMethod<[bigint], Electrician>,
  'findWorkOrderById' : ActorMethod<[bigint], WorkOrder>,
  'getAllElectricians' : ActorMethod<[], Array<Electrician>>,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getAvailableServices' : ActorMethod<[], Array<RepairServiceType>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkOrdersByElectrician' : ActorMethod<[bigint], Array<WorkOrder>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeElectrician' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCustomerRating' : ActorMethod<[bigint, bigint, string], undefined>,
  'submitWorkerRating' : ActorMethod<[bigint, bigint, string], undefined>,
  'updateElectrician' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [Speciality],
      [] | [boolean],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateWorkOrderPayment' : ActorMethod<
    [bigint, bigint, string, PaymentStatus],
    undefined
  >,
  'updateWorkOrderStatus' : ActorMethod<[bigint, WorkOrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];